<script lang="ts">
	import { enhance } from '$app/forms';
	import { Check, Inbox, Mail, Trash2 } from 'lucide-svelte';
	let { data } = $props();
</script>

<svelte:head><title>Pesan Masuk — Admin SAPALA 67</title></svelte:head>

<div class="mb-7"><p class="goal-label text-sapala-clay">KOMUNIKASI</p><h1 class="mt-2 font-heading text-3xl font-bold text-sapala-ink">Pesan Masuk</h1><p class="mt-1 text-sm text-sapala-ink/60">Tanggapi calon anggota, mitra, dan masyarakat dengan cepat.</p></div>

{#if data.messages.length}<div class="space-y-3">{#each data.messages as message}<article class="rounded-2xl border p-5 shadow-card {message.is_read ? 'border-sapala-ink/10 bg-white' : 'border-sapala-primary/25 bg-sapala-skysoft/25'}"><div class="flex flex-col justify-between gap-4 sm:flex-row"><div><div class="flex flex-wrap items-center gap-2"><h2 class="font-heading text-lg font-bold text-sapala-ink">{message.name}</h2>{#if !message.is_read}<span class="rounded-full bg-sapala-primary px-2 py-0.5 text-[10px] font-bold text-white">BARU</span>{/if}</div><a href="mailto:{message.email}" class="mt-1 inline-flex items-center gap-1 text-sm text-sapala-primary hover:underline"><Mail class="h-3.5 w-3.5" />{message.email}</a><p class="mt-4 max-w-3xl whitespace-pre-wrap text-sm leading-relaxed text-sapala-ink/75">{message.message}</p><p class="mt-4 text-xs text-sapala-ink/45">{message.created_at}</p></div><div class="flex h-fit gap-2">{#if !message.is_read}<form method="POST" action="?/read" use:enhance><input type="hidden" name="id" value={message.id} /><button class="inline-flex min-h-11 items-center gap-2 rounded-lg border border-sapala-primary/20 px-3 text-sm font-medium text-sapala-primary hover:bg-sapala-primary/10"><Check class="h-4 w-4" /> Sudah dibaca</button></form>{/if}<form method="POST" action="?/delete" use:enhance onsubmit={(event) => { if (!confirm('Hapus pesan ini?')) event.preventDefault(); }}><input type="hidden" name="id" value={message.id} /><button class="flex min-h-11 min-w-11 items-center justify-center rounded-lg text-sapala-red hover:bg-sapala-red/10" aria-label="Hapus pesan"><Trash2 class="h-4 w-4" /></button></form></div></div></article>{/each}</div>{:else}<div class="rounded-2xl border border-dashed border-sapala-ink/20 bg-white p-12 text-center"><Inbox class="mx-auto h-8 w-8 text-sapala-earth" /><p class="mt-4 font-medium text-sapala-ink">Belum ada pesan masuk.</p></div>{/if}
